from logger import log

log.error('Yes')